from enum import IntEnum


class OrderStatus(IntEnum):
    SUCCESS = (0,)
    CREATED = (1,)
    NOT_FOUND = (2,)
    WAITING_PRODUCTION_OR_SUPPLY = (3,)
    UNKNOWN_DRUG = (4,)
    UNKNOWN_ADMINISTRATION_ROUTE = (5,)
    ALREADY_PAID = (6,)
    ALREADY_OBTAINED = (7,)
    CANNOT_ASSIGN_CUSTOMER = (8,)
    CUSTOMER_NOT_ASSIGNED = (9,)
    INVALID_CUSTOMER = (10,)
    INVALID_DOCTOR = (11,)

    CANNOT_DELETE_CUSTOMER = (11,)
    CANNOT_BE_PAID = (12,)
    CANNOT_BE_OBTAINED = (13,)
    INTERNAL_ERROR = (14,)
