from enum import IntEnum


class OrderStatus(IntEnum):
    SUCCESS = (0,)
    ORDER_CREATED = (1,)
    ORDER_NOT_FOUND = (2,)
    ORDER_WAITING_PRODUCTION_OR_SUPPLY = (3,)
    UNKNOWN_ORDER_DRUG = (4,)
    UNKNOWN_ORDER_ADMINISTRATION_ROUTE = (5,)
    ORDER_IS_ALREADY_OBTAINED = (6,)
    ORDER_ID_ALREADY_PAID_FOR = (7,)
    INTERNAL_ERROR = (8,)
