"""unique_route_description

Revision ID: 08d3c6f99862
Revises: 8b41a0b824ad
Create Date: 2024-05-14 17:14:38.605958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d3c6f99862'
down_revision: Union[str, None] = '8b41a0b824ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'administration_routes', ['description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'administration_routes', type_='unique')
    # ### end Alembic commands ###
