"""added_mixture2.0

Revision ID: 3328018494f9
Revises: 931e506e423e
Create Date: 2024-05-14 20:13:14.017028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3328018494f9'
down_revision: Union[str, None] = '931e506e423e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixtures',
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('solvent', sa.String(), nullable=False),
    sa.Column('mixture_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['mixture_type_id'], ['mixture_types.id'], ),
    sa.PrimaryKeyConstraint('drug_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mixtures')
    # ### end Alembic commands ###
