"""added_salve

Revision ID: 3c7e0e103aba
Revises: 0ee0cb19561c
Create Date: 2024-05-14 20:55:52.829245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7e0e103aba'
down_revision: Union[str, None] = '0ee0cb19561c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salves',
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('active_substance', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('drug_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salves')
    # ### end Alembic commands ###
