"""added_reserved_drugs

Revision ID: 47c6b070276a
Revises: abdbea0b3ff0
Create Date: 2024-05-14 21:57:36.523421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c6b070276a'
down_revision: Union[str, None] = 'abdbea0b3ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserved_drugs',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('storage_item_id', sa.Integer(), nullable=False),
    sa.Column('drug_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['storage_item_id'], ['storage_items.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'storage_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserved_drugs')
    # ### end Alembic commands ###
