"""added_production_lab_workers

Revision ID: 599137aafa84
Revises: 47c6b070276a
Create Date: 2024-05-14 21:59:43.239250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599137aafa84'
down_revision: Union[str, None] = '47c6b070276a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_lab_workers',
    sa.Column('production_id', sa.Integer(), nullable=False),
    sa.Column('lab_worker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lab_worker_id'], ['lab_workers.id'], ),
    sa.ForeignKeyConstraint(['production_id'], ['production.id'], ),
    sa.PrimaryKeyConstraint('production_id', 'lab_worker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_lab_workers')
    # ### end Alembic commands ###
