"""added_pill

Revision ID: 80e529d51d60
Revises: 5ea3ad7bc15b
Create Date: 2024-05-14 20:28:43.840392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e529d51d60'
down_revision: Union[str, None] = '5ea3ad7bc15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pills',
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('weight_of_pill', sa.Integer(), nullable=False),
    sa.Column('pills_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('drug_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pills')
    # ### end Alembic commands ###
