"""added_tinctures

Revision ID: 90c793eb6e61
Revises: 7b21486aacf5
Create Date: 2024-05-14 21:08:56.212602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c793eb6e61'
down_revision: Union[str, None] = '7b21486aacf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tinctures',
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('drug_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tinctures')
    # ### end Alembic commands ###
