"""Heh

Revision ID: 948f2a2e4128
Revises: 8cccb8772fe9
Create Date: 2024-05-14 17:30:01.188990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '948f2a2e4128'
down_revision: Union[str, None] = '8cccb8772fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administration_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.drop_index('description', table_name='ADMINISTRATION_ROUTES')
    op.drop_table('ADMINISTRATION_ROUTES')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ADMINISTRATION_ROUTES',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('description', 'ADMINISTRATION_ROUTES', ['description'], unique=True)
    op.drop_table('administration_routes')
    # ### end Alembic commands ###
