"""make_order_customer_id_nullable

Revision ID: 9c1ef7b70088
Revises: cf94b4f3baec
Create Date: 2024-05-14 21:14:58.761432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c1ef7b70088'
down_revision: Union[str, None] = 'cf94b4f3baec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'customer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'customer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
