"""added_lab_worers_and_types_routes

Revision ID: a807a64960f4
Revises: 173164c444eb
Create Date: 2024-05-14 20:05:05.079517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a807a64960f4'
down_revision: Union[str, None] = '173164c444eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('drug_types_administration_routes',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['administration_routes.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['drug_types.id'], ),
    sa.PrimaryKeyConstraint('type_id', 'route_id')
    )
    op.alter_column('drugs', 'name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('drugs', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.create_unique_constraint(None, 'drugs', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drugs', type_='unique')
    op.alter_column('drugs', 'description',
               existing_type=sa.String(length=256),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('drugs', 'name',
               existing_type=sa.String(length=256),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_table('drug_types_administration_routes')
    op.drop_table('lab_workers')
    # ### end Alembic commands ###
