"""changed_diagnosis_length

Revision ID: ad1cb4ec6376
Revises: f1a67bd3d0da
Create Date: 2024-05-14 20:51:50.407577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad1cb4ec6376'
down_revision: Union[str, None] = 'f1a67bd3d0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescriptions', 'diagnosis',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.create_unique_constraint(None, 'prescriptions', ['diagnosis', 'patient_id', 'doctor_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptions', type_='unique')
    op.alter_column('prescriptions', 'diagnosis',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
