"""added_orders

Revision ID: cf94b4f3baec
Revises: 90c793eb6e61
Create Date: 2024-05-14 21:13:50.944055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf94b4f3baec'
down_revision: Union[str, None] = '90c793eb6e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('registration_datetime', sa.DateTime(), nullable=False),
    sa.Column('appointed_datetime', sa.DateTime(), nullable=True),
    sa.Column('obtaining_datetime', sa.DateTime(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
