"""added_storage_items

Revision ID: d1463d39da13
Revises: 9c1ef7b70088
Create Date: 2024-05-14 21:23:13.215490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1463d39da13'
down_revision: Union[str, None] = '9c1ef7b70088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('available_amount', sa.Integer(), nullable=False),
    sa.Column('original_amount', sa.Integer(), nullable=False),
    sa.Column('receipt_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_items')
    # ### end Alembic commands ###
