"""changed_datetime_to_date_somewhere

Revision ID: d7fc7acd1b20
Revises: d1463d39da13
Create Date: 2024-05-14 21:28:34.780686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7fc7acd1b20'
down_revision: Union[str, None] = 'd1463d39da13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'birthday',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('prescriptions', 'date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescriptions', 'date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('patients', 'birthday',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
