"""added_drug_cost_check_2

Revision ID: feb9c24954a3
Revises: f1c6d62ad176
Create Date: 2024-05-14 19:07:40.161149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb9c24954a3'
down_revision: Union[str, None] = 'f1c6d62ad176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
